[tool.poetry]
name = "hhintegrationtool"
version = "0.1.0"
description = ""
authors = ["Evgenia <evgeniabalackaa6@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
isort = "^6.0.1"
types-requests = "^2.32.0.20250328"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
